### DISCUSSION TITLE
r8152 driver not loading

### DISCUSSION THREAD

**Discussion by Hr46ph** [siderolabs/extensions#582] [Q&A]
Based off this request:
https://github.com/siderolabs/extensions/issues/581#issuecomment-2586666454

When I plug the USB NIC in the port, I see Talos logging it detects a new device:
```
 kern:    info: [2025-01-13T15:32:39.74124154Z]: usb 3-1: new SuperSpeed USB device number 2 using xhci_hcd
  SUBSYSTEM=usb
  DEVICE=+usb:3-1
```
I add machine config:
```
machine:
  network:
    hostname: cp01
    interfaces:
      - addresses:
          - 10.0.0.16/24
        dhcp: false
        interface: eth1
```
I reboot the node, but nowhere in dmesg do I see the driver being loaded. I do see the integrated NIC (also Realtek) is loading:
```
cp01: kern:    info: [2025-01-13T15:27:04.891166788Z]: r8169 0000:08:00.1 eth0: RTL8168fp/RTL8117, 50:81:40:98:c2:a1, XID 54b, IRQ 69
```

`tc get links -n cp01` only shows the eth0. There is no sign of the USB NIC.

Do I need to do anything special for this driver to load?

When I added the usb-modem driver extension it started working, but with the incorrect settings similar to what I saw on Archlinux.

**Comment by smira** [comment]
Wild guess - but might be https://github.com/siderolabs/extensions/tree/main/firmware/realtek-firmware?

We should probably figure out why it doesn't load without `usb-modem`

**Reply by Hr46ph** [reply]
Cheers for the quick response. I had that loaded before, but Im not sure whether that was with or without the usb-modem extension.

I can give it a try now, its easy enough.

For the usb-modem extension it was easy to check which drivers it contians, for the realtek-firmware I couldn't find the same. The closest is in the pkg.yaml, but it doesn't seem to contain a clear list with model numbers.

**Reply by smira** [reply]
Not sure if this NIC even requires firmware, it might print something in the boot log that it failed to load the firmware

**Reply by Hr46ph** [reply]
It did on Archlinux and it does according to the manufacturer which points to the Realtek website for the latest drivers. I compiled those on Arch and loaded it when it started fully working.

**Reply by Hr46ph** [reply]
Loading the realtek-firmware extension does not help. I also don't see any failures to load the driver, or any fail or error related to this (I see amd gpu failures, so i need to look into that but thats not for now).

Appreciate the help!

**Reply by Hr46ph** [reply]
with usb-modem driver extension, it starts working again.

```
cp01   network     LinkStatus   eth1              3         ether               80:3f:5d:fd:bb:1b                                 up           true
```
Except it doesn't load r8152, I cant find that in kernel logs. What I do see is its loading extra USB devices

```
cp01: kern:    info: [2025-01-13T16:06:01.600133743Z]: usbcore: registered new interface driver cdc_ether
 SUBSYSTEM=usb
 DEVICE=+usb:3-1:2.0
 SUBSYSTEM=usb
 DEVICE=+usb:3-1:2.0
 SUBSYSTEM=usb
 DEVICE=+usb:3-1:2.0
cp01: kern:    info: [2025-01-13T16:06:01.653736743Z]: cdc_ncm 3-1:2.0 eth1: register 'cdc_ncm' at usb-0000:01:00.0-1, CDC NCM (NO ZLP), 80:3f:5d:fd:bb:1b
 SUBSYSTEM=usb
 DEVICE=+usb:3-1:2.0
cp01: kern:    info: [2025-01-13T16:06:01.654853743Z]: usbcore: registered new interface driver cdc_ncm
cp01: kern:    info: [2025-01-13T16:06:01.659101743Z]: usbcore: registered new interface driver cdc_wdm
cp01: kern:    info: [2025-01-13T16:06:01.661725743Z]: usbcore: registered new interface driver cdc_mbim
```
talosctl output:
```
---
node: cp01
metadata:
    namespace: network
    type: LinkStatuses.net.talos.dev
    id: eth1
    version: 3
    owner: network.LinkStatusController
    phase: running
    created: 2025-01-13T16:06:01Z
    updated: 2025-01-13T16:06:02Z
spec:
    altNames:
        - enp1s0f0u1c2
        - enx803f5dfdbb1b
    index: 9
    type: ether
    linkIndex: 0
    flags: UP,BROADCAST,RUNNING,MULTICAST,LOWER_UP
    hardwareAddr: 80:3f:5d:fd:bb:1b
    permanentAddr: 80:3f:5d:fd:bb:1b
    broadcastAddr: ff:ff:ff:ff:ff:ff
    mtu: 1500
    queueDisc: pfifo_fast
    operationalState: up
    kind: ""
    slaveKind: ""
    busPath: usb-0000:01:00.0-1
    driver: cdc_ncm
    driverVersion: 6.12.6-talos
    firmwareVersion: CDC NCM (NO ZLP)
    linkState: true
    speedMbit: 705
    port: TwistedPair
    duplex: Half
```
I saw exactly this on Archlinux; 705 Mbit half duplex. On Arch I could see that it wasn't properly detected by running ethtool, none of the features were showing as detected. After loading the r8152 driver it showed all the features correctly.

So, to illustrate, I see this on Arch:
```
[10637.288164] usb 2-1: new SuperSpeed Plus Gen 2x1 USB device number 4 using xhci_hcd
[10637.317229] usb 2-1: New USB device found, idVendor=0bda, idProduct=8157, bcdDevice=30.00
[10637.317237] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[10637.317240] usb 2-1: Product: USB 10/100/1G/2.5G/5G LAN
[10637.317243] usb 2-1: Manufacturer: Realtek
[10637.317246] usb 2-1: SerialNumber: 0003000001
[10637.380928] usbcore: registered new interface driver cdc_ether
[10637.385208] usbcore: registered new interface driver cdc_ncm
[10637.389320] usbcore: registered new interface driver cdc_wdm
[10637.392683] usbcore: registered new interface driver cdc_mbim
[10637.396398] r8152: loading out-of-tree module taints kernel.
[10637.396413] r8152: module verification failed: signature and/or required key missing - tainting kernel
[10637.404707] usbcore: registered new device driver r8152-cfgselector
[10637.471113] cdc_ncm 2-1:2.0: MAC-Address: 80:3f:5d:fd:b6:98
[10637.471118] cdc_ncm 2-1:2.0: setting rx_max = 16384
[10637.471198] cdc_ncm 2-1:2.0: setting tx_max = 16384
[10637.471543] cdc_ncm 2-1:2.0 eth0: register 'cdc_ncm' at usb-0000:01:00.0-1, CDC NCM (NO ZLP), 80:3f:5d:fd:b6:98
[10637.477916] cdc_ncm 2-1:2.0 eth0: unregister 'cdc_ncm' usb-0000:01:00.0-1, CDC NCM (NO ZLP)
[10637.676817] r8152-cfgselector 2-1: reset SuperSpeed Plus Gen 2x1 USB device number 4 using xhci_hcd
[10637.732191] r8152 2-1:1.0: ram code version is wrong 0000(0013
[10637.822325] r8152 2-1:1.0 eth0: v2.19.2 (2024/10/21)
[10637.822335] r8152 2-1:1.0 eth0: This product is covered by one or more of the following patents:
               		US6,570,884, US6,115,776, and US6,327,625.

[10637.822388] usbcore: registered new interface driver r8152
[10637.872528] r8152 2-1:1.0 enp1s0f0u1: renamed from eth0
```

and ethtool:
```
❯ sudo ethtool enp1s0f0u1
Settings for enp1s0f0u1:
	Supported ports: [ MII ]
	Supported link modes:   10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Full
	                        2500baseT/Full
	                        5000baseT/Full
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Full
	                        2500baseT/Full
	                        5000baseT/Full
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Unknown! (255)
	Auto-negotiation: on
	Port: MII
	PHYAD: 32
	Transceiver: internal
	Supports Wake-on: pumbg
	Wake-on: d
        Current message level: 0x00007fff (32767)
                               drv probe link timer ifdown ifup rx_err tx_err tx_queued intr tx_done rx_status pktdata hw wol
	Link detected: no
	```
