### ISSUE TITLE
[drbd] drbd modules installed in /lib/modules/6.1.27-talos/extras instead of 6.1.28-talos

### ISSUE THREAD

**Issue by lidstah** [siderolabs/extensions#159]
Hi,

Wanted to test Piraeus/Linstor CSI, which needs the drbd extension, on Talos v1.4.4 (upgraded this morning), on my test cluster. I patched a test node machineconfig accordingly to piraeus documentation concerning Talos Linux (before patching the whole cluster's workers): 

```
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/drbd:9.2.2-v1.4.4
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```

and got this error in dashboard's log:

![2023-05-16-134955_807x71_scrot](https://github.com/siderolabs/extensions/assets/1635106/45b0dbe8-5aca-43c5-9cff-35df3832430c)

on a `talosctl list -n test_node /lib/modules/6.1.28-talos` (the actuel kernel used by my cluster VMs), no `extras` folder. But, on a `talosctl list -n test_node /lib/modules/6.1.27-talos` (the previous kernel), the `extras/drbd.ko` and `extras/drbd_transport_tcp.ko` kernel modules are present.

Should I force the use of the 6.1.27 kernel, or wait for next drbd extension version?

Sorry for my approximative english,

Best regards, and thank you for making Talos Linux.

Edit: replaced the test node by a fresh node, applied machineconfig, same behavior, drbd modules gets installed in `/lib/modules/6.1.27-talos/extras` instead of `/lib/modules/6.1.28-talos/extras`.
