### ISSUE TITLE
new kernel module fails to insert with "key was rejected by service"

### ISSUE THREAD

**Issue by djeebus** [siderolabs/extensions#227]
I'm working on creating an extension for the nvidia grid drivers (nvidia's open drivers don't support datacenter vgpus like the tesla line of cards). I've copied the `nonfree-kmod-nvidia` tree, in the hopes that they're similar enough that I can swap the linux installer and it would Just Work :tm: , but either I did something wrong or I'm missing some critical step in building and pushing the extensions. 

NOTE:
One other thing that might complicate all this is that I'm running fairly old hardware that requires GOAMD64=v1. [this](https://github.com/djeebus/talos-goamd64-v1/blob/main/.github/workflows/build.yaml) is the process I use to have github actions build all the artifacts for me. It currently builds everything, but I'm fairly certain I only use the `installer` and `talos` images. I'm also currently on `1.5.1`.

# build process
- copy the `nonfree-kmod-nvidia-pkg` package and create the [nonfree-kmod-nvidia-grid-pkg](https://github.com/siderolabs/pkgs/compare/release-1.5...djeebus:forked-1.5.1) package
- push it to ghcr.io/djeebus/talos/nonfree-kmod-nvidia-grid-pkg
- copy the `nonfree-kmod-nvidia` extension and create the [nonfree-kmod-nvidia-grid](https://github.com/siderolabs/extensions/compare/release-1.5...djeebus:talos-extensions:forked-1.5.1) extension
- push it to ghcr.io/djeebus/talos/nonfree-kmod-nvidia-grid

# installation

create the following patch:

```
# nvidia-vgpu.yaml
- op: add
  path: /machine/install/extensions
  value:
    - image: ghcr.io/djeebus/talos/nonfree-kmod-nvidia-grid:535.54.03-v1.5.1
- op: add
  path: /machine/kernel
  value:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
- op: add
  path: /machine/sysctls
  value:
    net.core.bpf_jit_harden: 1
```

apply the patch via:

```
talosctl  \
    --nodes $NODE \
    patch mc \
    --patch @nvidia-vgpu.yaml
```

trigger a reboot:

```
  talosctl \
    --nodes $NODE \
    upgrade --image=ghcr.io/djeebus/talos/installer:v1.5.1
```

# the error message
After all that, I get the following pair of messages in `dmesg` after a reboot:

```
$NODE: kern:  notice: [2023-09-12T16:35:58.881790988Z]: Loading of module with unavailable key is rejected
$NODE: user: warning: [2023-09-12T16:35:58.887564988Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \x5c"nvidia\x5c": load nvidia failed: key was rejected by service"}
```

Any advice you could give would be very welcome, thanks!
