### ISSUE TITLE
AWS ECR Image Credential Provider

### ISSUE THREAD

**Issue by Preisschild** [siderolabs/extensions#241]
# ECR Credential Provider Extension 

https://github.com/kubernetes/cloud-provider-aws/tree/master/cmd/ecr-credential-provider

This is a kubelet compatible credential provider helper, which generates short-lived tokens to authenticate against AWS ECR Registries. AWS' Elastic Container Registry (ECR) only allows short-lived tokens, so hard-coding credentials directly in `registryconfig.auth` doesnt work.

## Kubelet Credential Provider API

https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/

Kubelet can be configured with  the `--image-credential-provider-bin-dir` parameter, which configures the directory where the helper binary should be. The binary name (and other options) are then set over a `kind: CredentialProviderConfig` config, which is passed to kubelet with the `--image-credential-provider-config` parameter.

## Thoughts

I think for the first step, providing the `ecr-credential-provider` binary should be enough, because everything else can be configured in the Talosconfig.

**Comment by frezbo** [comment]
this can be brought in as an extension

**Comment by Preisschild** [comment]
Do you have a recommendation for location of the plugin binary directory?

**Comment by frezbo** [comment]
> Do you have a recommendation for the location of the plugin binary directory?
> 
> Rancher, for example, has it under `/var/lib/rancher/credentialprovider/bin`. Kubelet has no default.

extensions allow `/usr/local/bin` https://github.com/siderolabs/extensions?tab=readme-ov-file#rootfs-restrictions

**Comment by Preisschild** [comment]
Unfortunately, I can't put the binary directly inside `/usr/local/bin`, because I can't mount the binary to the kubelet container:

```
        - op: add
          path: /machine/kubelet/extraMounts
          value:
            - destination: /usr/local/bin/ecr-credential-provider
              type: bind
              source: /usr/local/bin/ecr-credential-provider
              options: [bind, ro]
 ```

This will fail because [Talos](https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/system/services/kubelet.go#L143) tries to `mkdir` the `source`, which won't work, because it's a file.

Mounting the whole `/usr/local/bin` directory also doesn't work, because the [`kubelet` binary is in there already](https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/system/services/kubelet.go#L117) and will be removed when the host dir is mounted.
