### ISSUE TITLE
Grub "error: out of memory" with nvidia extensions

### ISSUE THREAD

**Issue by mdallaire** [siderolabs/extensions#272]
Talos v1.5.5
nonfree-kmod-nvidia:535.54.03-v1.5.5
nvidia-container-toolkit:535.54.03-v1.13.5

Hardware: [NUC11PHKi7CAA](https://www.intel.com/content/www/us/en/products/sku/195961/intel-nuc-11-enthusiast-mini-pc-nuc11phki7caa/specifications.html) (UEFI boot)
64g RAM

After performing the initial installation with the vanilla metal-amd64.iso I apply the configuration with the nvidia extensions and kernel modules. All of which work well. When I perform a reboot with the `-m powercycle` option the machine won't boot with the following error:
![image](https://github.com/siderolabs/extensions/assets/23340663/46654d81-5412-4fc2-94fd-a7b19264646e)

Discussing with frezbo he mentionned this grub issue as a possible cause : https://bugs.launchpad.net/oem-priority/+bug/1842320

I performed other tests in proxmox running on the same hardware model by switching between UEFI and BIOS on VMs with the NVIDIA card in PCI passthrough but I was not able to reproduce the issue.

|Machine|Boot Mode| Result|
| - | - | - |
| Proxmox VM | BIOS | Works |
| Proxmox VM | UEFI | Works |
| Physical | UEFI |  grub OOM |
| Physical | BIOS | Not available for this hw|

**Comment by mdallaire** [comment]
The following schema (`e6584563021316c06939b85c8060bd4535499279ae9a6323d9356d7a2fcd7fb4`) and [ISO](https://factory.talos.dev/image/e6584563021316c06939b85c8060bd4535499279ae9a6323d9356d7a2fcd7fb4/v1.5.5/metal-amd64.iso) also result in the same behavior.
```
customization:
    extraKernelArgs:
        - nomodeset
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ucode
            - siderolabs/nvidia-container-toolkit
            - siderolabs/nonfree-kmod-nvidia
```
