### ISSUE TITLE
iscsi-tools : Containerd(ext-iscsid), going to restart forever

### ISSUE THREAD

**Issue by QJoly** [siderolabs/extensions#282]
Hi, 

I'm a new user of talos. The documentation is very complete and helped me a lot as a beginner. Thank you for all your hard work.

I'd like to use longhorn on all my Talos nodes, and as you know : I need to install open-iscsi. I tried the following configuration but it didn't worked well. The container ext-iscsid restarts forever.

```yaml
debug: false
persist: true
machine:
    type: controlplane
    token: redacted
    ca:
        crt: redacted
        key: redacted
    certSANs:
      - 127.0.0.1
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.28.3
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.5.5
        wipe: false
        extensions:
          - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
          - image: ghcr.io/siderolabs/qemu-guest-agent:8.1.3
```
Here is the output:
```
❯ talosctl services ext-iscsid status -n 192.168.128.10
NODE     192.168.128.10
ID       ext-iscsid
STATE    Waiting
HEALTH   ?
EVENTS   [Waiting]: Error running Containerd(ext-iscsid), going to restart forever: task "ext-iscsid" failed: exit code 127 (2s ago)
         [Running]: Started task ext-iscsid (PID 33404) for container ext-iscsid (2s ago)
         [Waiting]: Error running Containerd(ext-iscsid), going to restart forever: task "ext-iscsid" failed: exit code 127 (7s ago)
         [Running]: Started task ext-iscsid (PID 33339) for container ext-iscsid (7s ago)
         [Preparing]: Creating service runner (7s ago)
         [Preparing]: Running pre state (7s ago)
         [Waiting]: Waiting for service "containerd" to be "up", service "cri" to be "up", service "ext-tgtd" to be "up", network (7s ag
o)
         [Finished]: Service finished successfully (7s ago)
         [Stopping]: Aborting restart sequence (7s ago)
         [Waiting]: Error running Containerd(ext-iscsid), going to restart forever: task "ext-iscsid" failed: exit code 127 (11s ago)
         [Running]: Started task ext-iscsid (PID 33273) for container ext-iscsid (11s ago)
```

I'm using Talos v1.5.5, my nodes are virtual machines on a Proxmox hypervisor.

Thank you for your help
