### ISSUE TITLE
Support multiple version of tools in extension spec

### ISSUE THREAD

**Issue by frezbo** [siderolabs/extensions#29]
Some extensions like `open-iscsi`, `nvidia-toolkit` needs multiple tools/programs packaged together where-in each one might have different versions, currently we tag some extensions with the versions of different tools separated by a dash.

I propose to add support in the extension spec to define the versions of each tool/program separately and have a separate versioning schema for the extension itself.

```yaml
version: v1alpha1
metadata:
  name: <extension name>
  # this keeps the current versioning scheme for the overall extension
  version: <version of the package the extension installs>-<version of the extensions repo (tracks with talos version)>
  tools:
    <foo>: <version>
    <bar>: <version>
  author: Andrew Rynhard
  description: |
    <detailed description of the extension/package>
  ## The compatibility section is "optional" but highly recommended to specify a Talos version that
  ## has been tested and known working for this extension.
  compatibility:
    talos:
      version: ">= v1.0.0"
```

This also would allow to show the versions of tools shipped with an extension when running a `talosctl get extensions`
