### ISSUE TITLE
iscsi-tools extension fails to start on node startup

### ISSUE THREAD

**Issue by btkostner** [siderolabs/extensions#33]
Error message starting a node and viewing logs with `talosctl dmesg`:

```
192.168.1.153: user: warning: [2022-05-06T03:40:35.396887679Z]: [talos] service[ext-iscsid](Preparing): Running pre state
192.168.1.153: user: warning: [2022-05-06T03:40:35.474317679Z]: [talos] service[ext-iscsid](Preparing): Creating service runner
192.168.1.153: user: warning: [2022-05-06T03:40:35.558298679Z]: [talos] service[ext-iscsid](Failed): Failed to create runner: mkdir /usr/local/etc/iscsi/iscsid.conf: not a directory
```

`talosctl version`:

```
Client:
        Tag:         v1.0.0
        SHA:         80167fd2
        Built:       
        Go version:  go1.17.8
        OS/Arch:     darwin/amd64
Server:
        NODE:        192.168.1.153
        Tag:         v1.0.3
        SHA:         689c6e54
        Built:       
        Go version:  go1.17.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

Part of the configuration:

```yaml
version: v1alpha1
machine:
    type: controlplane
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.23.6
    install:
        extensions:
            - image: ghcr.io/siderolabs/intel-ucode:20220419
            - image: ghcr.io/siderolabs/iscsi-tools:v0.1.0
```
