### ISSUE TITLE
thunderbolt-udev extension

### ISSUE THREAD

**Issue by onedr0p** [siderolabs/extensions#530]
I'm trying to get my sonnet thunderbolt NICs working in Talos maintenance mode so I can use them to bootstrap Talos. However they aren't recognized by Talos until Talos installed via the following config with the existing thunderbolt extension.

```yaml
version: v1alpha1
machine:
...
  udev:
    rules:
      - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
  kernel:
    modules:
      - name: thunderbolt
      - name: thunderbolt_net
...
```

@frezbo mentioned it should be possible to create a new system extension that can add that udev rule in order for the NICs to be recognized in maintenance mode.

Another option would be to include the udev rule in the tb extension.
