### ISSUE TITLE
nut-client - "Connection Refused" despite being able to connect inside dnsutils, and router detects no connection attempt

### ISSUE THREAD

**Issue by Hacksawfred3232** [siderolabs/extensions#618]
Exactly as the title says. I can confirm that I can connect to the Network UPS Tools server from inside a container (which uses the IP of the host), the inter-network router sitting between my node and the NUT server can detect this connection. Yet when running the nut-client extension, it reports "Connection refused", yet the router reports no connection. Seems like the extension is broken at the moment, I sincerely doubt Cilium or Multus is causing this issue, as a connection from inside the container is working correctly.

Pod used to test:
```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

**Comment by frezbo** [comment]
You could test with `hostNetwork: true` in the pod spec, since extensions runs with hostnetworking

**Comment by Hacksawfred3232** [comment]
> You could test with `hostNetwork: true` in the pod spec, since extensions runs with hostnetworking

Pod can still connect in hostNetwork, "nut-client" still reporting "connection refused".

**Comment by frezbo** [comment]
is this with a dns name or an ip, maybe the dns resolution of nut-client is broken

**Comment by Hacksawfred3232** [comment]
> is this with a dns name or an ip, maybe the dns resolution of nut-client is broken
It's with an IP.
![Image](https://github.com/user-attachments/assets/2507a764-6146-488d-b458-77b8c89bee9d)

**Comment by frezbo** [comment]
what does `talosctl get extensionserviceconfig nut-client -o yaml` show

**Comment by Hacksawfred3232** [comment]
> what does `talosctl get extensionserviceconfig nut-client -o yaml` show

```
node: pinode1
metadata:
    namespace: runtime
    type: ExtensionServiceConfigs.runtime.talos.dev
    id: nut-client
    version: 1
    owner: runtime.ExtensionServiceConfigController
    phase: running
    created: 2025-02-22T23:02:32Z
    updated: 2025-02-22T23:02:32Z
spec:
    files:
        - content: |-
            MONITOR 192.168.10.10 1 monuser <password> secondary
            SHUTDOWNCMD "/sbin/poweroff"
          mountPath: /usr/local/etc/nut/upsmon.conf
```
