### ISSUE TITLE
Tailscale extension can't talk to its API

### ISSUE THREAD

**Issue by chrismsnz** [siderolabs/extensions#665]
Hi,

I installed the tailscale system extension. Some features require it to talk to its API, for example, configuring it with an oauth-style tokens:

```
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_AUTHKEY=tskey-client-<oauth-client-authkey>
```

This fails when it attempts to communicate with Tailscales HTTPS-secured API:
```
k8s-node1: Post "https://api.tailscale.com/api/v2/tailnet/-/keys": Post "https://api.tailscale.com/api/v2/oauth/token": tls: failed to verify certificate: x509: certificate signed by unknown authority
k8s-node1: boot: 2025/04/14 04:41:33 failed to auth tailscale: failed to auth tailscale: tailscale up failed: exit status 1
```

I suspect it needs CA root certificates, a proposed change might be to add the following mount to https://github.com/siderolabs/extensions/blob/main/network/tailscale/tailscale.yaml as is done in other containers: 
```
 - source: /etc/ssl/certs
      destination: /etc/ssl/certs
      type: bind
      options:
        - rbind
        - ro
```
