### ISSUE TITLE
NUT extension not working as intended

### ISSUE THREAD

**Issue by originaltrini0** [siderolabs/extensions#676]
I want to enable the nut-client in my Talos 1.9.5 cluster.
I have everything in place, but I don't see the client logging into the NUT server.
My extension config and other discovered data are below.
This nut configuration works just fine on my other Debian-based servers.
Other details can be found in the Slack @ https://taloscommunity.slack.com/archives/CG25RPZNE/p1744667665284729
Am I missing something in the configuration, or is this a genuine defect or bug?

Thanks

```
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client
configFiles:
  - content: |-
      MONITOR <UPS-NAME>@<NUT-SERVER> 1 <username> <password> secondary
      SHUTDOWNCMD "/sbin/poweroff"
    mountPath: /usr/local/etc/nut/upsmon.conf
```

```
❯ talosctl version -n 192.168.108.41
Client:
        Tag:         v1.9.5
        SHA:         d07f6daa
        Built:
        Go version:  go1.23.7
        OS/Arch:     darwin/arm64
Server:
        NODE:        192.168.108.41
        Tag:         v1.9.5
        SHA:         d07f6daa
        Built:
        Go version:  go1.23.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

```
❯ talosctl get extensionserviceconfigstatus -n 192.168.108.41 -o yaml
node: 192.168.108.41
metadata:
    namespace: runtime
    type: ExtensionServiceConfigStatuses.runtime.talos.dev
    id: nut-client
    version: 3
    owner: runtime.ExtensionServiceConfigFilesController
    phase: running
    created: 2025-04-15T01:19:58Z
    updated: 2025-04-26T17:10:05Z
spec:
    specVersion: "3"
```

```
❯ talosctl services -n 192.168.108.41
NODE             SERVICE      STATE     HEALTH   LAST CHANGE      LAST EVENT
192.168.108.41   apid         Running   OK       279h55m10s ago   Health check successful
192.168.108.41   auditd       Running   OK       279h55m22s ago   Health check successful
192.168.108.41   containerd   Running   OK       279h55m22s ago   Health check successful
192.168.108.41   cri          Running   OK       279h55m10s ago   Health check successful
192.168.108.41   dashboard    Running   ?        279h55m20s ago   Process Process(["/sbin/dashboard"]) started with PID 2431
192.168.108.41   etcd         Running   OK       279h55m4s ago    Health check successful
192.168.108.41   kubelet      Running   OK       279h55m7s ago    Health check successful
192.168.108.41   machined     Running   OK       279h55m22s ago   Health check successful
192.168.108.41   syslogd      Running   OK       279h55m21s ago   Health check successful
192.168.108.41   trustd       Running   OK       279h55m8s ago    Health check successful
192.168.108.41   udevd        Running   OK       279h55m22s ago   Health check successful
```

```
❯ talosctl processes -n 192.168.108.41 | grep 'nut'
--No Output--
```

**Comment by frezbo** [comment]
Seems `nut` extension is not installed, see `talosctl get extensions`, did you use an installer image from Image Factory with nut enabled?

**Comment by originaltrini0** [comment]
> Seems `nut` extension is not installed, see `talosctl get extensions`, did you use an installer image from Image Factory with nut enabled?

@frezbo, thanks for getting back to me.
`talosctl get extensions` returns an empty list, which is weird, as I am supposed to have other extensions loaded.

Here is what I did with Image Factory.
1. Created this customization file
```
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/nut-client
```

2. Submitted the file to Image Factory to generate the schematic ID.

3. Added the result of the previous step to machineconfig `machine.install.image` to install Talos Linux:
factory.talos.dev/installer/deee80e4ca4ed205ba87d67b33af7b023264d01ac97c1ce13ab083e6d70074f0:v1.9.5

Is this not the correct way to install extensions?

Thanks for any insight that you can provide.
