### ISSUE TITLE
Talos 1.10.0: can't suspend (nhi_runtime_suspend [thunderbolt] returned -110)

### ISSUE THREAD

**Issue by originaltrini0** [siderolabs/extensions#689]
Hello:

I am trying out Talos 1.10.0, but I have an issue using Talos with my Thunderbolt ports.
This is a fresh install of v1.10.0 on an Intel NUC (with the latest firmware). I did not encounter this error with v1.9.5.
Please let me know if you need further information from me to continue troubleshooting.

Thanks

```
talosctl -n 192.168.108.41 -e 192.168.108.41 version
Client:
        Tag:         v1.10.0
        SHA:         e6bd8304
        Built:
        Go version:  go1.24.2
        OS/Arch:     darwin/arm64
Server:
        NODE:        192.168.108.41
        Tag:         v1.10.0
        SHA:         e6bd8304
        Built:
        Go version:  go1.24.2
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 get systeminformation -o yaml
node: 192.168.108.41
metadata:
    namespace: hardware
    type: SystemInformations.hardware.talos.dev
    id: systeminformation
    version: 1
    owner: hardware.SystemInfoController
    phase: running
    created: 2025-05-02T21:52:56Z
    updated: 2025-05-02T21:52:56Z
spec:
    manufacturer: Intel(R) Client Systems
    productName: NUC11TNKi5
    version: M11922-404
    serialnumber: xxxxxxxxxxx
    uuid: 7913bacf-f80c-be1c-1db2-48210b25da47
    wakeUpType: Power Switch
    skuNumber: BNUC11TNKi50000/1/2
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 dmesg | grep thunderbolt
192.168.108.41: user: warning: [2025-05-02T20:03:25.350375517Z]: [talos] [initramfs] enabling system extension thunderbolt v1.10.0
192.168.108.41: kern:    info: [2025-05-02T20:03:26.066157517Z]: ACPI: bus type thunderbolt registered
192.168.108.41: kern:    info: [2025-05-02T20:03:26.066811517Z]: thunderbolt 0000:00:0d.2: enabling device (0000 -> 0002)
192.168.108.41: kern:    info: [2025-05-02T20:03:26.365241517Z]: thunderbolt 0000:00:0d.3: enabling device (0000 -> 0002)
192.168.108.41: kern:     err: [2025-05-02T20:03:45.441161517Z]: thunderbolt 0000:00:0d.2: can't suspend (nhi_runtime_suspend [thunderbolt] returned -110)
192.168.108.41: kern:     err: [2025-05-02T20:03:45.452825517Z]: thunderbolt 0000:00:0d.3: can't suspend (nhi_runtime_suspend [thunderbolt] returned -110)
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 read /proc/modules | grep thunderbolt
thunderbolt_net 49152 0 - Live 0xffffffffc0603000
thunderbolt 495616 1 thunderbolt_net, Live 0xffffffffc06b1000
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 ls /sys/class/net/ | grep -E 'NODE|thunderbolt'
NODE             NAME
--EMPTY RESULT--
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 get modules -o yaml
node: 192.168.108.41
metadata:
    namespace: runtime
    type: KernelModuleSpecs.runtime.talos.dev
    id: thunderbolt
    version: 1
    owner: runtime.KernelModuleConfigController
    phase: running
    created: 2025-05-02T20:03:27Z
    updated: 2025-05-02T20:03:27Z
spec:
    string: thunderbolt
    parameters: []
---
node: 192.168.108.41
metadata:
    namespace: runtime
    type: KernelModuleSpecs.runtime.talos.dev
    id: thunderbolt_net
    version: 1
    owner: runtime.KernelModuleConfigController
    phase: running
    created: 2025-05-02T20:03:27Z
    updated: 2025-05-02T20:03:27Z
spec:
    string: thunderbolt_net
    parameters: []
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 get extensions -o yaml | yq '. | select(.spec.metadata.name == "thunderbolt")'
node: 192.168.108.41
metadata:
  namespace: runtime
  type: ExtensionStatuses.runtime.talos.dev
  id: 3
  version: 1
  owner: runtime.ExtensionStatusController
  phase: running
  created: 2025-05-02T20:03:25Z
  updated: 2025-05-02T20:03:25Z
spec:
  image: 3.sqsh
  metadata:
    name: thunderbolt
    version: v1.10.0
    author: Igor Rzegocki
    description: |
      This system extension provides Thunderbolt/USB4 drivers kernel modules built against a specific Talos version.
      This driver enables Thunderbolt/USB4 devices, including networking.
    compatibility:
      talos:
        version: '>= v1.5.0'
```

```
talosctl -n 192.168.108.41 -e 192.168.108.41 get devices -o yaml | yq '. | select(.spec.product == "*Thunderbolt*")'
node: 192.168.108.41
metadata:
  namespace: hardware
  type: PCIDevices.hardware.talos.dev
  id: 0000:00:07.0
  version: 1
  owner: hardware.PCIDevicesController
  phase: running
  created: 2025-05-02T20:03:26Z
  updated: 2025-05-02T20:03:26Z
spec:
  class: Bridge
  subclass: PCI bridge
  vendor: Intel Corporation
  product: 'Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #1'
  class_id: "0x06"
  subclass_id: "0x04"
  vendor_id: "0x8086"
  product_id: "0x9a25"
  driver: pcieport
---
node: 192.168.108.41
metadata:
  namespace: hardware
  type: PCIDevices.hardware.talos.dev
  id: 0000:00:07.2
  version: 1
  owner: hardware.PCIDevicesController
  phase: running
  created: 2025-05-02T20:03:26Z
  updated: 2025-05-02T20:03:26Z
spec:
  class: Bridge
  subclass: PCI bridge
  vendor: Intel Corporation
  product: 'Tiger Lake-LP Thunderbolt 4 PCI Express Root Port #2'
  class_id: "0x06"
  subclass_id: "0x04"
  vendor_id: "0x8086"
  product_id: "0x9a27"
  driver: pcieport
---
node: 192.168.108.41
metadata:
  namespace: hardware
  type: PCIDevices.hardware.talos.dev
  id: 0000:00:0d.0
  version: 1
  owner: hardware.PCIDevicesController
  phase: running
  created: 2025-05-02T20:03:26Z
  updated: 2025-05-02T20:03:26Z
spec:
  class: Serial bus controller
  subclass: USB controller
  vendor: Intel Corporation
  product: Tiger Lake-LP Thunderbolt 4 USB Controller
  class_id: "0x0c"
  subclass_id: "0x03"
  vendor_id: "0x8086"
  product_id: "0x9a13"
  driver: xhci_hcd
---
node: 192.168.108.41
metadata:
  namespace: hardware
  type: PCIDevices.hardware.talos.dev
  id: 0000:00:0d.2
  version: 1
  owner: hardware.PCIDevicesController
  phase: running
  created: 2025-05-02T20:03:26Z
  updated: 2025-05-02T20:03:26Z
spec:
  class: Serial bus controller
  subclass: USB controller
  vendor: Intel Corporation
  product: 'Tiger Lake-LP Thunderbolt 4 NHI #0'
  class_id: "0x0c"
  subclass_id: "0x03"
  vendor_id: "0x8086"
  product_id: "0x9a1b"
  driver: thunderbolt
---
node: 192.168.108.41
metadata:
  namespace: hardware
  type: PCIDevices.hardware.talos.dev
  id: 0000:00:0d.3
  version: 1
  owner: hardware.PCIDevicesController
  phase: running
  created: 2025-05-02T20:03:26Z
  updated: 2025-05-02T20:03:26Z
spec:
  class: Serial bus controller
  subclass: USB controller
  vendor: Intel Corporation
  product: 'Tiger Lake-LP Thunderbolt 4 NHI #1'
  class_id: "0x0c"
  subclass_id: "0x03"
  vendor_id: "0x8086"
  product_id: "0x9a1d"
  driver: thunderbolt
```
