### ISSUE TITLE
Kubelet cannot exec ECR Credential Provider

### ISSUE THREAD

**Issue by IonitaCatalin** [siderolabs/extensions#706]
### Description

We are encountering an issue with our Talos cluster (Talos version 1.10.2, Kubernetes version 1.33), which consists of 6 nodes (3 control plane nodes and 3 worker nodes). We're attempting to integrate the ECR credential provider, but are facing the following error after installing the extension and configuring credentialProviderConfig under the kubelet settings in the MachineConfig:

`10.25.2.10: {"ts":1748003206479.928,"caller":"plugin/plugin.go:440","msg":"Failed getting credential from external registry credential provider: error execing credential provider plugin ecr-credential-provider for image REDACTED
.dkr.ecr.eu-central-1.amazonaws.com/REDACTED: fork/exec /usr/local/lib/kubelet/credentialproviders/ecr-credential-provider: no such file or directory: "}`

We manually copied the ecr-credential-provider binary to the expected path, and verified the binary with the following output:

`ecr-credential-provider: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=dcca742bcebddbb85cc6de228550c2d4213492e3, stripped` 

Despite this, the kubelet still reports that the binary cannot be found. We would appreciate any guidance or suggestions on resolving this issue.

Also the MachineConfig that we used:

```
machine:
  install:
    image: factory.talos.dev/installer/0348e0009fc8ea56f8ef3b36aa2976c2c1f4494f530376fe5d6b6f122c332ad2:v1.10.2
    diskSelector:
      wwid: REDACTED
    wipe: true

  network:
    hostname: worker-01
    interfaces:
      - deviceSelector:
          hardwareAddr: REDACTED
          physical: true
        dhcp: false
        vlans:
          - vlanId: 4001
            mtu: 1400
            dhcp: false
            addresses:
              - 10.25.2.10/24
            routes:
              - network: 0.0.0.0/0
                gateway: 10.25.2.1
              - network: 10.25.0.0/16
                gateway: 10.25.2.1
  disks: 
    - device:  /dev/disk/by-id/REDACTED
      partitions:
        - mountpoint: /var/lib/longhorn
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
    kubePrism:
      enabled: false
      port: 7445

  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.33.0
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    credentialProviderConfig:
      apiVersion: kubelet.config.k8s.io/v1
      kind: CredentialProviderConfig
      providers:
        - name: ecr-credential-provider
          matchImages:
            - "*.dkr.ecr.*.amazonaws.com"
            - "*.dkr.ecr.*.amazonaws.com.cn"
            - "*.dkr.ecr-fips.*.amazonaws.com"
            - "*.dkr.ecr.us-iso-east-1.c2s.ic.gov"
            - "*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"
          defaultCacheDuration: "12h"
          apiVersion: credentialprovider.kubelet.k8s.io/v1
  env:
    AWS_ACCESS_KEY_ID: REDACTED
    AWS_SECRET_ACCESS_KEY:  REDACTED

```

### Logs

Mentioned above

### Environment

- Talos version: V1.10.2
- Kubernetes version: V1.33
- Platform: Hetzner
