### ISSUE TITLE
Upgrade to image including `nut-client` results in unbootable Raspberry Pi 4.

### ISSUE THREAD

**Issue by reitermarkus** [siderolabs/extensions#718]
I have been using the following schematic for my Raspberry Pi nodes:

```
overlay:
  image: siderolabs/sbc-raspberrypi
  name: rpi_generic
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/iscsi-tools
      - siderolabs/nut-client
      - siderolabs/util-linux-tools
```

After a recent power outage I had to reset these nodes, so I tried re-installing using the above schematic. After waiting for a couple of minutes the nodes were not pingable.

I then tried installing the vanilla image, which made the nodes pingable and `talosctl apply-config` work.

I then tried upgrading these nodes to the above schematic again. The upgrade starts successfully, but after  rebooting, the node becomes unpingable again.

I then tried the same process again, first upgrading from the vanilla image to the vanilla image as a sanity check, which works. Then upgrading to an image only containing `siderolabs/iscsi-tools`, which also works. Then upgrading to an image containing `siderolabs/iscsi-tools` and `siderolabs/util-linux-tools`, which also works. Then upgrading to the schematic above, which again makes the node unpingable.

In all cases, Talos v1.10.3 was used.

Previously, the nodes were running v1.9.3 with all three extensions, so I will try to re-install 1.9.3 to check.
